### PR TITLE
Logo update

### PR DESCRIPTION
**Pull request by realkemon**
Removed .ai files to not depend on proprietary software.
Fixed incorrect dimensions and spacing in the logo.
Logo concepts for League will follow in the coming days.
After merge, links on this page need to be updated. https://github.com/etlegacy/etlegacy/wiki/Branding
I'll take care of that.

### CODE REVIEW

**Review by mittermichal — COMMENTED** [review]
the spacing changes looks good to me

**Comment by rmarquis** [comment]
The branding page just requires the removal of the `.ai` links.
Ensure to refresh the browser cache to see the fixed logos.

I'll update the in-game splashscreen later today.

**Comment by mittermichal** [comment]
Don't know where are the logos links, but if u want to ensure they are loaded without refreshing browser cache then just append something unique like `?v=2` to the end of image url.

**Comment by rmarquis** [comment]
FYI, I updated the in-game logos with the new version. Website has also been adjusted, and the wiki page cleaned up.

**Comment by realkemon** [comment]
Thank you @rmarquis!

**Pull request merged**
